//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfScribeInstallCustomAction.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PdfScribeInstallCustomAction.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to EnumMonitors in winspool.drv succeeded with a zero size buffer - unexpected error..
        /// </summary>
        internal static string EnumerateMonitorUnexpectedError {
            get {
                return ResourceManager.GetString("EnumerateMonitorUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to EnumPrinterDrivers in winspool.drv succeeded with a zero size buffer - unexpected error..
        /// </summary>
        internal static string EnumeratePrinterDriverUnexpectedError {
            get {
                return ResourceManager.GetString("EnumeratePrinterDriverUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination file {0} was not copied/created - it already exists..
        /// </summary>
        internal static string FileNotCopiedAlreadyExists {
            get {
                return ResourceManager.GetString("FileNotCopiedAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer driver file was not copied. Exception message: {0}.
        /// </summary>
        internal static string FileNotCopiedPrinterDriver {
            get {
                return ResourceManager.GetString("FileNotCopiedPrinterDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is being used by another process. File was not deleted..
        /// </summary>
        internal static string FileNotDeletedInUse {
            get {
                return ResourceManager.GetString("FileNotDeletedInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is read-only, or its file permissions do not allow for deletion..
        /// </summary>
        internal static string FileNotDeletedUnauthorized {
            get {
                return ResourceManager.GetString("FileNotDeletedUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port configuration failed..
        /// </summary>
        internal static string InfoInstallConfigPortFailed {
            get {
                return ResourceManager.GetString("InfoInstallConfigPortFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not copy printer driver files..
        /// </summary>
        internal static string InfoInstallCopyDriverFailed {
            get {
                return ResourceManager.GetString("InfoInstallCopyDriverFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add redirected port..
        /// </summary>
        internal static string InfoInstallPortFailed {
            get {
                return ResourceManager.GetString("InfoInstallPortFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port monitor installation failed..
        /// </summary>
        internal static string InfoInstallPortMonitorFailed {
            get {
                return ResourceManager.GetString("InfoInstallPortMonitorFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer driver installation failed..
        /// </summary>
        internal static string InfoInstallPrinterDriverFailed {
            get {
                return ResourceManager.GetString("InfoInstallPrinterDriverFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add printer..
        /// </summary>
        internal static string InfoInstallPrinterFailed {
            get {
                return ResourceManager.GetString("InfoInstallPrinterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial uninstallation failure. Function {0} returned false..
        /// </summary>
        internal static string InstallRollBackFailureAtFunction {
            get {
                return ResourceManager.GetString("InstallRollBackFailureAtFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not enable 64-bit file system redirection..
        /// </summary>
        internal static string NativeCouldNotEnable64Redirection {
            get {
                return ResourceManager.GetString("NativeCouldNotEnable64Redirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not revert 64-bit file system redirection..
        /// </summary>
        internal static string NativeCouldNotRevert64Redirection {
            get {
                return ResourceManager.GetString("NativeCouldNotRevert64Redirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add port monitor {0}.
        /// </summary>
        internal static string PortMonitorAddFailed {
            get {
                return ResourceManager.GetString("PortMonitorAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port monitor {0} already installed..
        /// </summary>
        internal static string PortMonitorAlreadyInstalled {
            get {
                return ResourceManager.GetString("PortMonitorAlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove port monitor dll..
        /// </summary>
        internal static string PortMonitorDllRemoveFailed {
            get {
                return ResourceManager.GetString("PortMonitorDllRemoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not enumerate port monitors..
        /// </summary>
        internal static string PortMonitorRetrieveFailed {
            get {
                return ResourceManager.GetString("PortMonitorRetrieveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port monitor successfully installed..
        /// </summary>
        internal static string PortMonitorSuccessInstalled {
            get {
                return ResourceManager.GetString("PortMonitorSuccessInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer configured..
        /// </summary>
        internal static string PrinterConfigured {
            get {
                return ResourceManager.GetString("PrinterConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add Aivika printer driver..
        /// </summary>
        internal static string PrinterDriverAddFailed {
            get {
                return ResourceManager.GetString("PrinterDriverAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer drivers copied or already exist..
        /// </summary>
        internal static string PrinterDriverExisted {
            get {
                return ResourceManager.GetString("PrinterDriverExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer driver installed..
        /// </summary>
        internal static string PrinterDriverInstalled {
            get {
                return ResourceManager.GetString("PrinterDriverInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove Aivika printer driver..
        /// </summary>
        internal static string PrinterDriverRemoveFailed {
            get {
                return ResourceManager.GetString("PrinterDriverRemoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve printer driver directory..
        /// </summary>
        internal static string PrinterDriverRetrieveFailed {
            get {
                return ResourceManager.GetString("PrinterDriverRetrieveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not enumerate printer drivers..
        /// </summary>
        internal static string PrinterDriversEnumerateFailed {
            get {
                return ResourceManager.GetString("PrinterDriversEnumerateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirection port added..
        /// </summary>
        internal static string RedirectionPortAdded {
            get {
                return ResourceManager.GetString("RedirectionPortAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add port configuration to registry. Exception message: {0}.
        /// </summary>
        internal static string RegistryConfigNotAdded {
            get {
                return ResourceManager.GetString("RegistryConfigNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete port configuration from registry. Exception message: {0}.
        /// </summary>
        internal static string RegistryConfigNotDeleted {
            get {
                return ResourceManager.GetString("RegistryConfigNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add Aivika virtual printer..
        /// </summary>
        internal static string VirtualPrinterAddFailed {
            get {
                return ResourceManager.GetString("VirtualPrinterAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete Aivika virtual printer..
        /// </summary>
        internal static string VirtualPrinterDeleteFailed {
            get {
                return ResourceManager.GetString("VirtualPrinterDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual printer installed..
        /// </summary>
        internal static string VirtualPrinterInstalled {
            get {
                return ResourceManager.GetString("VirtualPrinterInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win32 error code {0}..
        /// </summary>
        internal static string Win32Error {
            get {
                return ResourceManager.GetString("Win32Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not disable Wow64 file system redirection..
        /// </summary>
        internal static string Wow64DisableFailed {
            get {
                return ResourceManager.GetString("Wow64DisableFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not reenable Wow64 file system redirection..
        /// </summary>
        internal static string Wow64ReenableFailed {
            get {
                return ResourceManager.GetString("Wow64ReenableFailed", resourceCulture);
            }
        }
    }
}
